server:
  port: 10010

file:
  size: 2MB

spring:
  servlet:
    multipart:
      max-file-size: ${file.size}
  main:
    allow-bean-definition-overriding: true
  application:
    name: common-service
  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
        namespace: d9071204-66d3-4d7b-9dbb-16dcbd337a3c
        cluster-name: DEFAULT

logging:
  config: classpath:log4j2.xml
