server:
  port: 10010

file:
  size: 5MB

spring:
  servlet:
    multipart:
      max-file-size: ${file.size}
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://txyun5.linshiyou.cn:3306/financial_final_contest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: zzh
    password: zzh
  application:
    name: common-service
  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
        namespace: d9071204-66d3-4d7b-9dbb-16dcbd337a3c
        cluster-name: DEFAULT
        ip: txyun.linshiyou.cn

mybatis-plus:
  configuration:
    #日志打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:cn/linshiyou/financialFinalContest/common/dao/mapper/xml/*.xml

logging:
  config: classpath:log4j2.xml
