server:
  port: 10011

spring:
  profiles:
    include:
      - seata
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://txyun5.linshiyou.cn:3306/financial_final_contest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: zzh
    password: zzh
  application:
    name: goods-service
  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
        namespace: d9071204-66d3-4d7b-9dbb-16dcbd337a3c
        cluster-name: DEFAULT
  rabbitmq:
    host: 199.115.231.73
    port: 5672
  redis:
    host: txyun.linshiyou.cn
    port: 6379
    password: gL0(bG0&jM
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0

mybatis-plus:
  configuration:
    #日志打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:cn/linshiyou/financialFinalContest/goods/dao/mapper/xml/*.xml

logging:
  config: classpath:log4j2.xml
