server:
  port: 9100

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
        namespace: d9071204-66d3-4d7b-9dbb-16dcbd337a3c
        cluster-name: DEFAULT
#    gateway:
#      routes:
#        - id: account-service
#          uri: lb://account-service
#          predicates:
#            - Path=/account-service/**
#          filters:
#            - StripPrefix= 1