server:
  port: 10013

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: search-service
  elasticsearch:
    rest:
      uris: https://txyun5.linshiyou.cn:9201
      connection-timeout: 1000
      read-timeout: 1000

  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
        namespace: d9071204-66d3-4d7b-9dbb-16dcbd337a3c
        cluster-name: DEFAULT
  rabbitmq:
    host: 199.115.231.73
    port: 5672

logging:
  config: classpath:log4j2.xml
