server:
  port: 10100

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
        namespace: d9071204-66d3-4d7b-9dbb-16dcbd337a3c
        cluster-name: DEFAULT
    gateway:
      routes:
        - id: common-service
          uri: lb://common-service
          predicates:
            - Path=/common-service/**
          filters:
            - StripPrefix= 1
        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/goods-service/**
          filters:
            - StripPrefix= 1
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login-service/**
          filters:
            - StripPrefix= 1
        - id: msm-service
          uri: lb://msm-service
          predicates:
            - Path=/msm-service/**
          filters:
            - StripPrefix= 1