server:
  port: 8204

spring:
  profiles:
    include:
      - redis
  main:
    allow-bean-definition-overriding: true
  application:
    name: msm-service
  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
        namespace: d9071204-66d3-4d7b-9dbb-16dcbd337a3c
        cluster-name: DEFAULT


