server:
  port: 8204

spring:
  profiles:
    include:
      - redis
  main:
    allow-bean-definition-overriding: true
  application:
    name: msm-service
  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
#        namespace: d9071204-66d3-4d7b-9dbb-16dcbd337a3c
        namespace: 045f0ce7-1b60-4b65-abec-e03c7d0a0fa6
        cluster-name: DEFAULT
#        ip: txyun.linshiyou.cn
  rabbitmq:
    host: txyun.linshiyou.cn
    port: 5672
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://txyun5.linshiyou.cn:3306/financial_final_contest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: zzh
    password: zzh

