server:
  port: 10014

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: swap-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://txyun5.linshiyou.cn:3306/financial_final_contest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: zzh
    password: zzh
  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
        namespace: d9071204-66d3-4d7b-9dbb-16dcbd337a3c
        cluster-name: DEFAULT
  rabbitmq:
    host: 199.115.231.73
    port: 5672

logging:
  config: classpath:log4j2.xml
