server:
  port: 10014

spring:
  profiles:
    include:
      - seata
  main:
    allow-bean-definition-overriding: true
  application:
    name: swap-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://txyun5.linshiyou.cn:3306/financial_final_contest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: zzh
    password: zzh
  cloud:
    nacos:
      discovery:
        server-addr: txyun.linshiyou.cn:8848
        namespace: 045f0ce7-1b60-4b65-abec-e03c7d0a0fa6
        cluster-name: DEFAULT
#        ip: txyun5.linshiyou.cn
  rabbitmq:
    host: txyun.linshiyou.cn
    port: 5672
mybatis-plus:
  configuration:
    #日志打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:cn/linshiyou/financialFinalContest/swap/dao/mapper/xml/*.xml


# 不加配置可能出错
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000


logging:
  config: classpath:log4j2.xml
